<div class="spacer"></div>
<div id="startchange"></div>
<div class="page-header">
		<h1>Terms & Conditions</h1>
</div>
<div class="container">
<p >Welcome to <a href="http://www.hippogriff.com/" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=http://www.hippogriff.com&amp;source=gmail&amp;ust=1487421076925000&amp;usg=AFQjCNHIhsvWjAUh91aXIB4oEW9kFMjsPw">www.hippogriff.com</a>. is an online shopping website which offers array of products at amazing prices. Please read this terms and conditions carefully. In following these terms &amp; conditions, references to &#8216;You&#8217;, means the &#8216;User&#8217; registering and accessing the website. &#8216;Service Providers&#8217; means the third party service providers. We reserve the right to amend this Notice at any time and your use of this website following any amendments will represent your agreement to be bound by these terms and conditions as amended.  We therefore recommend that each time you access our website you read these terms and conditions.</p>
<p >THESE TERMS, INCLUDING THIS INTRODUCTORY SECTION, CREATE A BINDING LEGAL CONTRACT BETWEEN YOU AND US. BY USING THE COMPANY SERVICES, YOU REPRESENT AND WARRANT THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT ACCEPT THESE TERMS, YOU MUST NOT USE AND ARE NOT AUTHORIZED TO USE ALL OR ANY PORTION OF THE COMPANY SERVICES.</p>
<p >ELIGIBILITY:</p>
<p >For the purposes of this agreement, “you” means a user who pays for access to the website as or user who accesses or uses the site. If you are a child under 13 years of age, we may need your parent or guardians consent before allowing you to use the service. This Site is intended for use by you only if you are 18 years of age or older. The service is not available to any users previously removed from the service by other Ecommerce websites.</p>
<p >If you are using or opening an account to use the site on behalf of a company, entity or organization (each a “Subscribing Entity”), then you represent and warrant that you: (i) are an authorized representative of that subscribing entity with the authority to bind such entity to these Terms, and (ii) agree to be bound by these Terms on behalf of such subscribing entity.</p>
<p >Additionally, users are prohibited from transferring their Hippogriff account to another party. If you do not qualify, you may not use the Hippogriff Service.</p>
<p >By using this website, you agree to be bound by all of the terms and conditions mentioned on the website. These terms and conditions apply to all users of the site. Hippogriff reserve right to limit the number of user accounts per household. Products and services are offered to private users only not to commercial retailers.</p>
<p >MEMBERSHIP</p>
<p >In order to access the Service provided on this website, you must become a member. You must complete registration by providing certain information as set out on our membership/registration page.  Please also refer to our Privacy Policy linked on our home page for information relating to our collection, storage and use of the details you provide on registration.</p>
<p >You agree to ensure that your registration details, including your name, address, contact number and email address, are true and accurate at all times and you undertake to update your registration details from time to time when they change.  If we become aware that either your name and/or email address is incorrect, we reserve the right to immediately cancel your registration and acceptance for registration in the future will be at our discretion.</p>
<p >You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your password or account. In this endeavor company requires you to regularly notify company of any unauthorized use of your password, account or breach of security. There will be no liability of company for any loss or damage arising due to non-compliance terms and conditions of website.</p>
<p >HIPPOGRIFF SERVICE</p>
<p >Subject to the terms and conditions of this Agreement, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Service for your personal, non-commercial use only and as permitted by the features of the Service. Hippogriff reserves all rights not expressly granted herein in the Service and the Hippogriff Content (as defined below). Hippogriff may terminate this license at any time for any reason or no reason.</p>
<p >HIPPOGRIFF ACCOUNTS</p>
<p >Your Hippogriff account gives you access to the services and functionality that we may establish and maintain from time to time and in our sole discretion. By connecting to Hippogriff with a third-party service (for example, Facebook or Twitter), you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service.</p>
<p >You may never use another User’s account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You must notify Hippogriff immediately of any breach of security or unauthorized use of your account. Hippogriff will not be liable for any losses caused by any unauthorized use of your account.</p>
<p >You may control your User profile and how you interact with the Service by changing the settings in your “account settings” page. By providing Hippogriff, your email address you consent to our using the email address to send you Service-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the Service and newsletters, special offers. If you do not want to receive such email messages, you may opt out or change your preferences in your “account settings or just unsubscribe” page. Opting out may prevent you from receiving email messages regarding updates, improvements, or offers.</p>
<p >OUR PROPRIETARY RIGHTS</p>
<p >Except for your User Content, the videos and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the “Hippogriff Content”), and all Intellectual Property Rights related thereto, are the exclusive property of Hippogriff and its licensors (including other Users who post User Content to the Service). Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any Hippogriff Content. Use of the Hippogriff Content for any purpose not expressly permitted by this Agreement is strictly prohibited.</p>
<p >You may choose to or we may invite you to submit comments or ideas about the Service, including without limitation about how to improve the Service or our products (“Ideas”). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place Hippogriff under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, Hippogriff does not waive any rights to use similar or related ideas previously known to Hippogriff, or developed by its employees, or obtained from sources other than you.</p>
<p >HYPERLINKS</p>
<p >This website may from time to time contain hyperlinks to other websites.  Such links are provided for convenience only and we take no responsibility for the content and maintenance of or privacy compliance by any linked website.  Any hyperlink on our website to another website does not imply our endorsement, support, or sponsorship of the operator of that website nor of the information and/or products or services which they provide.</p>
<p >You may link our website without our consent.  Any such linking will be entirely your responsibility and at your expense.  By linking, you must not alter any of our website&#8217;s contents including any intellectual property notices and you must not frame or reformat any of our pages, files, images, text or other materials.</p>
<p >PRIVACY &amp; SECURITY</p>
<p >We care about the privacy of our Users. You understand that by using the Services you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in our Privacy Policy, and to have your personally identifiable information collected, used, transferred to and processed in India. Hippogriff cares about the integrity and security of your personal information. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper provide your personal information at your own risk.</p>
<p >INTELLECTUAL PROPERTY RIGHTS</p>
<p >We claim no intellectual property rights over the material you submit post, transmit or display on, or through, the Service. Your profile and materials uploaded remain yours. The ownership of any content created by a user of the Service in the context of a course remains the property of that user. However, be aware that by setting your profile or pages to be viewed publicly, you are allowing others to view your content.</p>
<p >The copyright to all content that has been created by us, including applets, graphics, images, layouts and text belongs to us or we have a licence to use those materials.</p>
<p >All trademarks, brands and logos generally identified either with the symbols TM or ® which are used on this website are either owned by us or we have a licence to use them. Your access to our website does not license you to use those marks in any commercial way without our prior written permission.</p>
<p >If you provide us with Comments, you acknowledge that you are responsible for the content of such material including its legality, originality and copyright.</p>
<p >You will not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on the Site. Hippogriff’s content is not for resale. Your use of the Site does not entitle you to make any unauthorized use of any protected content, and in particular you will not delete or alter any proprietary rights or attribution notices in any content. You will use protected content solely for your personal use, and will make no other use of the content without the express written permission of Hippogriff and the copyright owner. You agree that you do not acquire any ownership rights in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of Hippogriff or our licensors except as expressly authorized by these Terms.</p>
<p >Unless otherwise stated, all fees are quoted in Indian Rupees. You are responsible for paying all fees and applicable taxes associated with the Site in a timely manner with a valid payment method that is accepted by us in our sole discretion. If your payment method fails or your account is past due, then we may collect fees owed using other collection mechanisms. This may include charging other payment methods on file with us and/or retaining collection agencies and legal counsel. We may also block your access to site pending resolution of any amounts due by you to us.</p>
<p >USE OF COMMUNICATION SERVICES</p>
<p >The Site may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, “Communication Services”), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service.</p>
<p >By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another&#8217;s computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect information about others, including e-mail addresses, without their consent; violate any applicable laws or regulations.</p>
<p >Hippogriff has no obligation to monitor the Communication Services. However, Hippogriff reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. Hippogriff reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>
<p >Hippogriff reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Hippogriff sole discretion.</p>
<p >Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. Hippogriff does not control or endorse the content, messages or information found in any Communication Service and, therefore, Hippogriff specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Hippogriff spokespersons, and their views do not necessarily reflect those of Hippogriff.</p>
<p >Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you upload the materials.</p>
<p>&nbsp;</p>
<p >POSTING</p>
<p >The Company has the right to reject or refuse to post any material you have provided, remove any material from the website whether or not the material goes against any of these conditions, or restrict, suspend or stop your access to all or any part of the website at any time.</p>
<p >PRICES</p>
<p >The prices for products are mentioned in the website and are incorporated into these Terms by reference. The prices are in Indian rupees. The prices, products and services are subject to change at Team Hippogriff’s discretion. The discount code / cash back applied on an order have a limit of 1 code / coupon / cash back per order.</p>
<p >REFUND</p>
<p >The amount would be refunded within 45 working days excluding (<span class="aBn" tabindex="0" data-term="goog_1066537863"><span class="aQJ">Saturday</span></span> and <span class="aBn" tabindex="0" data-term="goog_1066537864"><span class="aQJ">Sunday</span></span> or as per company’s convenience) from the date of cancellation. You are requested to check your bank statement thoroughly to make sure that you have received your refund amount. Goods can be returned and refunded only if damaged when or before it reaches you.</p>
<p >TERMINATION/ACCESS RESTRICTION</p>
<p >Hippogriff reserves the right, in its sole discretion, to terminate your access to the Site and the related services or any portion thereof at any time, without notice. To the maximum extent permitted by law, this agreement is governed by the laws of India and you hereby consent to the exclusive jurisdiction and venue of courts in India ,in all disputes arising out of or relating to the use of the Site. Use of the Site is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms, including, without limitation, this section.</p>
<p >You agree that no joint venture, partnership, employment, or agency relationship exists between you and Hippogriff as a result of this agreement or use of the Site. Hippogriff’s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Hippogriff right to comply with governmental, court and law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by Hippogriff with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect.</p>
<p >Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and Hippogriff with respect to the Site and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Hippogriff with respect to the Site. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be written in English.</p>
<p >INDEMNITY</p>
<p >You agree to defend, indemnify and hold harmless Hippogriff and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising out of or related to: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) User Content or any other information or content that is submitted via your account including without limitation misleading, false or inaccurate information; (vi) negligent or wilful misconduct; or (vii) any other party’s access and use of other appropriate security code.</p>
<p >NO WARRANTY</p>
<p >THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, HIPPOGRIFF, ITS SUBSIDIARIES, ITS AFFILIATES, AND ITS LICENSORS DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE SERVICE.</p>
<p >SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS AND EXCLUSIONS UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<p >HIPPOGRIFF DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE HIPPOGRIFF SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE, AND HIPPOGRIFF WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>
<p >CANCELLATION OF FRAUDULENT ORDERS</p>
<p >To provide a safe and secure shopping experience, we regularly monitor transactions for fraudulent activity. In the event of detecting any suspicious activity, Hippogriff.com reserves the right to cancel all past, pending and future orders without any liability. Hippogriff also reserves the right to refuse or cancel orders in scenarios like inaccuracies in pricing of product on website and stock unavailability. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your card has been charged, the said amount will be reversed to your Card Account. Any promotional voucher used for the cancelled orders may not be refunded.</p>
<p >INTERNATIONAL USERS</p>
<p >The Service is controlled, operated and administered by Hippogriff from our offices within India. If you access the Service from a location outside India, you are responsible for compliance with all local laws. You agree that you will not use the Hippogriff’s Content accessed through <a href="http://www.hippogriff.com/" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=http://www.Hippogriff.com&amp;source=gmail&amp;ust=1487421076926000&amp;usg=AFQjCNHXg0SwEWeOtPVYV5aAbURLsIHmBw">http://www.Hippogriff.com</a> in any country or in any manner prohibited by any applicable laws, restrictions or regulations.</p>
<p >LIMITATION OF LIABILITY</p>
<p >TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL HIPPOGRIFF, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THIS SERVICE. UNDER NO CIRCUMSTANCES WILL HIPPOGRIFF BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
<p >TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HIPPOGRIFF ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. IN NO EVENT SHALL HIPPOGRIFF, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO HIPPOGRIFF HEREUNDER OR $100.00, WHICHEVER IS GREATER.</p>
<p >THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF HIPPOGRIFF HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
<p >SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE EXCLUSIONS AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<p >The Service is controlled and operated from facilities in India. Hippogriff makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable in India and local laws and regulations, including but not limited to export and import regulations. You may not use the Service if you are a resident of a country embargoed by India, or are a foreign person or entity blocked or denied by the India government. Unless otherwise explicitly stated, all materials found on the Service are solely directed to individuals, companies, or other entities located in India.</p>
<p >GENERAL</p>
<p >Assignment This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Hippogriff without restriction. Any attempted transfer or assignment in violation hereof shall be null and void.</p>
<p >Notification Procedures and Changes to the Agreement Hippogriff may provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to you via email notice, written or hard copy notice, or through posting of such notice on our website, as determined by Hippogriff in our sole discretion. Hippogriff reserves the right to determine the form and means of providing notifications to our Users, provided that you may opt out of certain means of notification as described in this Agreement. Hippogriff is not responsible for any automatic filtering you or your network provider may apply to email notifications we send to the email address you provide us. Hippogriff may, in its sole discretion, modify or update this Agreement from time to time, and so you should review this page periodically. When we change the Agreement in a material manner, we will update the ‘last modified’ date at the bottom of this page. Your continued use of the Service after any such change constitutes your acceptance of the new Terms of Service. If you do not agree to any of these terms or any future Terms of Service, do not use or access (or continue to access) the Service.</p>
<p >Entire Agreement/Severability This Agreement, together with any amendments and any additional agreements you may enter into with Hippogriff in connection with the Service, shall constitute the entire agreement between you and Hippogriff concerning the Service. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect, except that in the event of unenforceability of the universal Class Action/Jury Trial Waiver, the entire arbitration agreement shall be unenforceable.</p>
<p >No Waiver No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Hippogriff failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision.</p>
<p >Contact Please contact us at <a href="mailto:info@kslegal.co.in" target="_blank">info@kslegal.co.in</a> with any questions regarding this Agreement.</p>
<p >Disputes Any dispute or claim relating in any way to your use of any Hippogriff Service, or to any products or sold or distributed by Hippogriff or through Hippogriff.com will be resolved by binding arbitration.</p>
<p >Applicable Law and Jurisdiction Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The Courts/Tribunals in New Delhi shall have exclusive jurisdiction to try any disputes or suit arising out of this Agreement.</p>
</div>